package spring.boardgame.registerboardgame.model;
// Generated 19-May-2016 11:52:48 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.JoinTable;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * Gamesession generated by hbm2java
 */
@Entity
@Table(name = "gamesession")              
public class Gamesession implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.AUTO)
     @Column(name = "id", updatable = false, nullable = false)
     private Long id;
     
     @Column(name = "dato")
     private String dato;
     
     @Column(name = "scenarioID")
     private Long scenarioId;
     
     //@OneToOne(cascade = CascadeType.ALL)
     //@JoinColumn(name = "registrar")
     //private Player registrar;
     
     @Column(name = "competitors")
     private Integer competitors;
     
     @Column(name = "spillID")
     private Integer spillet;
     
     @OneToMany(fetch = FetchType.EAGER,cascade=CascadeType.ALL)
     @JoinColumn(name="sesjonID")
     private Set<Participation> deltakelser = new HashSet<Participation>(0);

    public Gamesession() {
    }

    public Gamesession(Integer spillId, String dato, Long scenarioId, Integer registrar, Long orgId, Integer comp, Player reg) {
       this.spillet = spillId;
       this.dato = dato;
       this.scenarioId = scenarioId;
       //this.registrar = reg;
       this.id = orgId;
       this.competitors = comp;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Integer getSpillet() {
        return this.spillet;
    }
    public void setSpillet(Integer spillId) {
       this.spillet = spillId;
    }    
    
    public void setDeltakelser(Set<Participation> lis) {
        this.deltakelser = lis;
    }
    public Set<Participation> getDeltakelser() {
        return this.deltakelser;
    }    
    
    public String getDato() {
        return this.dato;
    }
    
    public void setDato(String dato) {
        this.dato = dato;
    }
    public Long getScenarioId() {
        return this.scenarioId;
    }
    
    public void setScenarioId(Long scenarioId) {
        this.scenarioId = scenarioId;
    }
    //public Player getRegistrar() {
    //    return this.registrar;
   // }
    
    //public void setRegistrar(Player registrar) {
   //     this.registrar = registrar;
    //}
    public Integer getCompetitors() {
        return this.competitors;
    }
    
    public void setCompetitors(Integer orgId) {
        this.competitors = orgId;
    }




}


