package spring.boardgame.registerboardgame.model.display;
// Generated 19-May-2016 11:52:48 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.JoinTable;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import spring.boardgame.registerboardgame.model.*;

/**
 * Gamesession generated by hbm2java
 */
@Entity
@Table(name = "gamesession")              
public class SingleGamesession implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.AUTO)
     @Column(name = "id", updatable = false, nullable = false)
     private Long id;
     
     @Column(name = "dato")
     private String dato;
     

     private Scenario scenario = null;
     
     @Column(name = "scenarioID")
     private Long scenarioId;
     
     @OneToOne(cascade = CascadeType.ALL)
     @JoinColumn(name = "registrar")
     private Player registrar;
     
     @Column(name = "competitors")
     private Integer competitors;
     
     @OneToOne(cascade = CascadeType.ALL)
     @JoinColumn(name = "spillID")
     private DisplayGame spillet;
     
     @OneToMany(fetch = FetchType.EAGER,cascade=CascadeType.ALL)
     @JoinColumn(name="sesjonID")
     @OrderBy("POSISJON")
     private Set<DisplayParticipation> deltakelser = new HashSet<DisplayParticipation>(0);

    public SingleGamesession() {
    }

    public SingleGamesession(DisplayGame spillId, String dato, Scenario scenarioId, Long orgId, Integer comp,Player reg) {
       this.setSpillet(spillId);
       this.setDato(dato);
       this.setScenario(scenarioId);
       this.setRegistrar(reg);
       this.setId(orgId);
       this.setCompetitors(comp);
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public DisplayGame getSpillet() {
        return this.spillet;
    }
    public void setSpillet(DisplayGame spillId) {
       this.spillet = spillId;
    }    
    
    public void setDeltakelser(Set<DisplayParticipation> lis) {
        this.deltakelser = lis;
    }
    public Set<DisplayParticipation> getDeltakelser() {
        return this.deltakelser;
    }    
    
    public String getDato() {
        return this.dato;
    }
    
    public void setDato(String dato) {
        this.dato = dato;
    }
    public Scenario getScenario() {
        return this.scenario;
    }
    
    public void setScenario(Scenario scenarioId) {
        this.scenario = scenarioId;
    }
    public Player getRegistrar() {
        return this.registrar;
    }
    
    public void setRegistrar(Player registrar) {
        this.registrar = registrar;
    }
    public Integer getCompetitors() {
        return this.competitors;
    }
    
    public void setCompetitors(Integer orgId) {
        this.competitors = orgId;
    }
    
    public Long getScenarioId() {
        return this.scenarioId;
    }
    
    public void setScenarioId(Long scenarioId) {
        this.scenarioId = scenarioId;
    }




}


